schema {
    query: Query
}
type Query {
    user(id: String!): User
    services(
        name: String!,
        latitude: Float,
        longitude: Float,
        radius: Float,
        limit: Int,
        page: Int
    ): [Service!]
    GetProvidersByServiceAndLocation(
        name: String!,
        latitude: Float,
        longitude: Float,
        radius: Float,
        limit: Int,
        page: Int
    ): [Provider!]
    GetAddress(id: Int!): Address
}
