version: "3"
services:
  styleblitz-shared:
    container_name: styleblitz-shared
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "PG_ROOT_PASSWORD=styleblitz"
      - "PG_DATABASE=styleblitz"
      - "PG_USER=root"
      - "PG_PASSWORD=styleblitz"
      - "PG_HOST=styleblitz-pg"
      - "PG_PORT=5432"
      - "PG_SSL=disable"
      - "MIGRATION_PATH=migrations/query"
      - "APP_NAME=styleblitz"
      - "ROOT_DIRECTORY=/go/src/github.com/synergydesigns/stylesblitz-server"
    volumes:
      - ./:/go/src/github.com/synergydesigns/stylesblitz-server
    # restart: always
    expose:
      - 80
    ports:
      - "8083:8090"
    depends_on:
      # - styleblitz-mysql
      - styleblitz-pg
    # command: sleep 9999999
    command: >
      bash -c "make migrate"
      # bash -c "make build && make supervise"
    networks:
      styleblitz_default:

  styleblitz-pg:
    container_name: styleblitz-pg
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: styleblitz
      POSTGRES_USER: root
      POSTGRES_DB: styleblitz
      FATHOM_DATABASE_SSLMODE: disable
    volumes:
     - styleblitze-pg:/var/lib/postgresql
    networks:
      styleblitz_default:
    ports:
      - "5432:5432"

networks:
  styleblitz_default:
    driver: bridge

volumes:
  styleblitze-pg: