WSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: style blitz serverless application.


Resources:
  GraphqlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda/bin/graphql
      Runtime: go1.x
      MemorySize: 256
      Environment:
        Variables:
          PG_ROOT_PASSWORD: test
          PG_DATABASE: test
          PG_USER: root
          PG_PASSWORD: 
          PG_HOST: localhost
          PG_PORT: 5432
          PG_SSL: disable
          MIGRATION_PATH: ../query
          APP_NAME: styleblitz
          AWS_SECRET_ACCESS_KEY:
          AWS_S3_BUCKET:
          AUTHENTICATION_SECRET:
          PASSWORD_SECRET:
          GO_ENV:
      Events:
        GraphqlAPI:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
        PreflightAPI:
          Type: Api
          Properties:
            Path: /graphql
            Method: options
  GraphqliFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda/bin/graphqli
      Runtime: go1.x
      Environment:
        Variables:      
          GRAPHQL_URL: /graphql

      Events:
        Api:
          Type: Api
          Properties:
            Path: /playground
            Method: get