WSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: style blitz serverless application.

Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token',Access-Control-Allow-Origin'"
      AllowOrigin: "'*'"

Resources:
  GraphqlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda/bin/graphql
      Runtime: go1.x
      MemorySize: 256
      Environment:
        Variables:
          PG_ROOT_PASSWORD: test
          PG_DATABASE: test
          PG_USER: root
          PG_PASSWORD: 
          PG_HOST: localhost
          PG_PORT: 5432
          PG_SSL: disable
          MIGRATION_PATH: ../query
          APP_NAME: styleblitz
      Events:
        Api:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
  GraphqliFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda/bin/graphqli
      Runtime: go1.x
      Environment:
        Variables:      
          GRAPHQL_URL: /graphql

      Events:
        Api:
          Type: Api
          Properties:
            Path: /playground
            Method: get