AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: style blitz serverless application.
Resources:
  GraphqlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/graphql
      Runtime: go1.x
      Environment:
        Variables:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: 
          DATABASE_HOST: localhost
          MYSQL_PORT: 3306
          MIGRATION_PATH: ../query
          APP_NAME: styleblitz
      Events:
        Api:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
  GraphqliFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/graphqli
      Runtime: go1.x
      Events:
        Api:
          Type: Api
          Properties:
            Path: /playground
            Method: get