type CartType {
	product: Product
	service: Service
}

type Cart {
	id: ID!
	userId: String
	vendorID: String
	createdAt: Timestamp
	updatedAt: Timestamp
	cartType: CartType
	type: String
	quantity: Int
}

type ProductCart {
	id: ID!
	vendorId: String
	productId: String
	shopId: String
  cartId: String
  quantity: Int
	product: Product
}

input ServiceCartInput {
	vendorID: String!
	serviceID: Int!
	quantity: Int
}

input ProductCartInput {
	vendorID: String!
	productID: String!
	quantity: Int
}

input CartUpdateInput {
	cartID:   String!
	quantity: Int!
	type:     String!
	typeID:   String!
}

input CartInput {
	vendorID:   String!
	quantity:   Int!
	type:       String!
	typeID:     String!
}

extend type Mutation {
	createProductCart(input: ProductCartInput!): ProductCart
	updateProductCart(input: CartUpdateInput!): ProductCart
	deleteProductCart(cart_id: ID!): Boolean
	createServiceCart(input: ServiceCartInput!): ServiceCart
	updateServiceCart(input: CartUpdateInput!): ServiceCart
	deleteServiceCart(cart_id: ID!): Boolean
	createCart(input: CartInput!): Cart
	updateCart(input: CartUpdateInput!): Cart
	deleteCart(cart_id: ID!): Boolean
}

extend type Query {
	getProductsCart(user_id: ID): [ProductCart]
	getServicesCart(user_id: ID): [ServiceCart]
	getAllCarts(user_id: ID): [Cart]
}