type VendorCategory {
	ID:          ID!
	name:        String
	description: String
}

input VendorCategoryInput {
	name: String!
	description: String
	vendor_id: String!
}

input VendorCategoryInputUpdate {
	vendor_id: String!
	name: String
	description: String
}

extend type Mutation {
	createVendorCategory(input: VendorCategoryInput!): VendorCategory
	updateVendorCategory(input: VendorCategoryInputUpdate!, category_id: Int!): VendorCategory
	deleteVendorCategory(category_id: Int!): Boolean
}

extend type Query {
	getAllCategories(vendorId: String): [VendorCategory]
}