type ServiceReview {
	id:         ID!
	userId:     String
	vendorID:   String
	createdAt:  Timestamp
	updatedAt:  Timestamp
  serviceID:  Int!
	text:       String!
	rating:     String
	parentID:   Int
	replies:    [ServiceReview]
}

input ServiceReviewInput {
	vendorID:   String!
  serviceID:  Int!
	text:       String!
	rating:     String
	parentID:   Int
}

input ServiceReviewUpdateInput {
	id:         Int!
	text:       String!
	rating:     String
}

extend type Mutation {
	createReview(input: ServiceReviewInput!): ServiceReview
	UpdateReview(input: ServiceReviewUpdateInput!): ServiceReview
}

extend type Query {
  getServiceReviews(service_id: Int!): [ServiceReview]
}
