type User {
    # ID is a unique idetifer
    # Of the user that owns this resource
    id:             ID!
    email:          String
    name:           String
    phone:          Int
    password:       String
    ProfileImage:   String
    WallImage:      String
    Bio:            String
}