// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/synergydesigns/stylesblitz-server/shared/models"
)

type Opening struct {
	ID     uint64  `json:"ID"`
	ShopID uint64  `json:"shopID"`
	From   *string `json:"from"`
	To     *string `json:"to"`
	Day    *string `json:"day"`
}

type Review struct {
	ID     uint64       `json:"ID"`
	User   *models.User `json:"user"`
	ShopID uint64       `json:"shopID"`
	Rating *int         `json:"rating"`
	Review *string      `json:"review"`
}
